sudo: false
language: bash
os:
  - linux
  - osx
env:
  global:
    - PYMANAGE_ROOT=./opt
    - PYMANAGE_PATH=./bin
    - PYMANAGE_TMP=./tmp
matrix:
  allow_failures:
    - os: linux
install:
  - mkdir ./opt ./bin ./tmp
  - ./pymanage install 3.5.0
  - ./pymanage link 3.5.0
script:
  - sh ./test_pymanage.sh

