language: bash
os:
  - linux
  - osx
env:
  global:
    - PYM_ROOT=~/.local/opt
    - PYM_PATH=~/.local/bin
    - PYM_TMP=~/.local/tmp
install:
  - mkdir -p ~/.local/{opt,bin,tmp}
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo apt-get build-dep python; fi
  - ./pym install 3.5.0
  - ./pym link 3.5.0
script:
  - sh ./test_pym.sh

